<?php

global $routes;

$routes = array (
    'app' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida, saudável, sono, mente, zen, idade, corporal, sensor, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, trueage, true, age, wearables, pulseira, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis',
        'css'         => array('home'),
        'features'    => array('install-app'),
        'include'     => 'app',
        'body_class'  => null,
        'menu_item'   => 'app',
    ),
    'home' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida, saudável, sono, mente, zen, idade, corporal, sensor, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, trueage, true, age, wearables, pulseira, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis',
        'css'         => array('home'),
        'features'    => array('install-app'),
        'include'     => 'home',
        'body_class'  => null,
        'menu_item'   => 'home',
    ),
    'carenet' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida saudável, sono, mente, zen, idade, corporal, sensor, corporal, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, true, age, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis.',
        'css'         => array(),
        'features'    => array(),
        'include'     => 'carenet',
        'body_class'  => null,
        'menu_item'   => 'carenet',
    ),
    'carenet.longevidade' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida saudável, sono, mente, zen, idade, corporal, sensor, corporal, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, true, age, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis.',
        'css'         => array(),
        'features'    => array(),
        'include'     => 'carenet.longevidade',
        'body_class'  => null,
        'menu_item'   => 'carenet',
    ),
    'carenet.4-dimensoes' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida saudável, sono, mente, zen, idade, corporal, sensor, corporal, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, true, age, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis.',
        'css'         => array(),
        'features'    => array(),
        'include'     => 'carenet.4-dimensoes',
        'body_class'  => null,
        'menu_item'   => 'carenet',
    ),
    'carenet.comunidade' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida saudável, sono, mente, zen, idade, corporal, sensor, corporal, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, true, age, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis.',
        'css'         => array(),
        'features'    => array(),
        'include'     => 'carenet.comunidade',
        'body_class'  => null,
        'menu_item'   => 'carenet',
    ),
    'carenet.desafios' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida saudável, sono, mente, zen, idade, corporal, sensor, corporal, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, true, age, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis.',
        'css'         => array(),
        'features'    => array(),
        'include'     => 'carenet.desafios',
        'body_class'  => null,
        'menu_item'   => 'carenet',
    ),
    'carenet.trueage' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida saudável, sono, mente, zen, idade, corporal, sensor, corporal, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, true, age, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis.',
        'css'         => array(),
        'features'    => array(),
        'include'     => 'carenet.trueage',
        'body_class'  => null,
        'menu_item'   => 'carenet',
    ),
    'condicoes' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida saudável, sono, mente, zen, idade, corporal, sensor, corporal, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, true, age, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis.',
        'css'         => array(),
        'features'    => array(),
        'include'     => 'conditions',
        'body_class'  => 'silverBg blackText',
        'menu_item'   => 'conditions',
    ),
    'contato' => array (
        'title'       => 'Carenet no Celular – sua vida mais saudável',
        'description' => 'Monitore suas atividades físicas, seu sono, peso e muito mais. Baixe agora o app grátis e tenha uma vida mais saudável.',
        'keywords'    => 'Carenet, celular, baixe, aplicativo, saúde, atividade física, sono, peso, emagrecimento, mente, zen, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis',
        'css'         => array(),
        'features'    => array('contact.js'),
        'include'     => 'contact',
        'body_class'  => null,
        'menu_item'   => 'contact',
    ),
    'klip' => array (
        'title'       => 'Carenet no Celular – sua vida mais saudável',
        'description' => 'Monitore suas atividades físicas, seu sono, peso e muito mais. Baixe agora o app grátis e tenha uma vida mais saudável.',
        'keywords'    => 'Carenet, celular, baixe, aplicativo, saúde, atividade física, sono, peso, emagrecimento, mente, zen, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis',
        'css'         => array('klip'),
        'features'    => array(),
        'include'     => 'klip',
        'body_class'  => 'silverBg blackText',
        'menu_item'   => 'klip',
    ),
    'perguntas-frequentes' => array (
        'title'       => 'Carenet Longevidade. Você, melhor.',
        'description' => 'Fique mais saudável e viva mais tempo. Monitore suas atividades físicas, seu sono, descubra sua idade corporal, desafie e compartilhe com seus amigos.',
        'keywords'    => 'Carenet, saúde, longevidade, vida saudável, sono, mente, zen, idade, corporal, sensor, corporal, biosensor, biossensor, mobile, healthcare, mhealth, health, tracker, true, age, pulseiras, fitness, bbb, fitbit, jawbone, fuelband, misfit, mybasis.',
        'css'         => array(),
        'features'    => array(),
        'include'     => 'faq',
        'body_class'  => null,
        'menu_item'   => 'faq',
    ),
);
