  <!-- slider wrapper starts -->
  <div class="sliderOuterWrapper noPadding" style="margin-right: 5%; margin-left: 5%; margin-top: 8%; border-style: solid; border-width: 1px; border-color:#ffffff;">
    <div class="sliderWrapper">
      <div class="mainSlider" id="mainSlider">
           <a href=""><img src="/assets/img-custom/app/01-960-pt.png" alt="" /></a>
           <a href=""><img src="/assets/img-custom/app/02-960-pt.png" alt="" /></a>
           <a href=""><img src="/assets/img-custom/app/03-960-pt.png" alt="" /></a>
           <a href=""><img src="/assets/img-custom/app/04-960-pt.png" alt="" /></a>
           <a href=""><img src="/assets/img-custom/app/05-960-pt.png" alt="" /></a>
      </div>
    </div>
  </div>
  <!-- slider wrapper ends -->

  <div class="div_image_resized">
      <img src="/assets/img-custom/klip-carenet.png" alt=""/>
  </div>

  <div class="gettoknow">
      <a class="gettoknow_klip gettoknow_img" href="/klip">
          <img src="/assets/img-custom/icon-dispositivo.png" alt=""/>
          <br/>
          <span class="cnText">Klip</span>
      </a>
      <img class="gettoknow_main" src="/assets/img-custom/arrows.png" alt=""/>
      <a class="gettoknow_app gettoknow_img" href="/app">
          <img src="/assets/img-custom/icon-app.png" alt=""/>
          <br/>
          <span class="cnText">App</span>
      </a>
  </div>