
    <div class="halfLogo">
        <img src="/assets/img-custom/logo-spacer-b.png" alt=""/>
    </div>

    <div class="carenet_info_box div_image_resized">
        <img src="/assets/img-custom/main-4dimensoes_pt.png" alt="" />
    </div>

    <div class="content">
        <img src="/assets/img-custom/icon-track.png" style="vertical-align:middle; display:inline;">
        <h3 style="display:inline;">Acompanhe</h3>
        <br/>
        <p>Seja por dados que você mesmo insere no
            APP ou por informações vindas do sensor
            ligado ao seu corpo no momento das
            atividades, o sistema ajudará você a medir
            sua evolução de uma forma desafiadora e
            divertida.</p>
        <br/>
        <img src="/assets/img-custom/icon-chart.png" style="vertical-align:middle; display:inline;">
        <h3 style="display:inline;">Veja os Gráficos</h3>
        <p>Todos os resultados das 4 categorias em
            gráficos de fácil entendimento, que
            ajudarão você a visualizar o melhor
            caminho para atingir seus objetivos de
            saúde.</p>
        <br/>
        <br/>
    </div>
    <div class="contentFooter div_image_resized">
        <img src="/assets/img-custom/carenet-bottom.png" alt=""/>
    </div>
    <br/>
    <div class="btnsSaibaMais">
        <span>SAIBA MAIS SOBRE:</span>
        <a href="/carenet/longevidade">Longevidade</a>
        <a href="/carenet/comunidade">Comunidade</a>
        <a href="/carenet/desafios">Desafios</a>
        <a href="/carenet/trueage">TrueAge&reg;</a>
    </div>

    <div class="div_image_resized">
        <img src="/assets/img-custom/klip-carenet.png" alt=""/>
    </div>

    <div class="gettoknow">
        <a class="gettoknow_klip gettoknow_img" href="/klip">
            <img src="/assets/img-custom/icon-dispositivo.png" alt=""/>
            <br/>
            <span class="cnText">Klip</span>
        </a>
        <img class="gettoknow_main" src="/assets/img-custom/arrows.png" alt=""/>
        <a class="gettoknow_app gettoknow_img" href="/app">
            <img src="/assets/img-custom/icon-app.png" alt=""/>
            <br/>
            <span class="cnText">App</span>
        </a>
    </div>


