
    <div class="halfLogo">
        <img src="/assets/img-custom/logo-spacer-b.png" alt=""/>
    </div>

    <div class="carenet_info_box div_image_resized">
        <img src="/assets/img-custom/main-comunidade_pt.png" alt="" />
    </div>

    <div class="content">
        <img src="/assets/img-custom/icon-comunidade-uniao.png" style="vertical-align:middle; display:inline;">
        <h3 style="display:inline;">O Poder da União</h3>
        <br/>
        <p>A Carenet promove a ideia de formar uma comunidade, envolvendo os seus amigos e família, independente da distância e fuso horário.</p>
        <br/>
        <img src="/assets/img-custom/icon-comunidade-familia.png" style="vertical-align:middle; display:inline;">
        <h3 style="display:inline;">Família</h3>
        <p>Use a nossa tecnologia para saber sobre a saúde de seus pais, filhos e cuidar melhor da sua família.</p>
        <br/>
        <img src="/assets/img-custom/icon-comunidade-compartilhando.png" style="vertical-align:middle; display:inline;">
        <h3 style="display:inline;">Compartilhando Saúde</h3>
        <p>As redes socias podem ajudar-nos a atingir o que não poderíamos atingir sozinhos. Compartilhe resultados com seus amigos e atinja suas metas.</p>
        <br/>
        <br/>
    </div>
    <div class="contentFooter div_image_resized">
        <img src="/assets/img-custom/carenet-bottom.png" alt=""/>
    </div>
    <br/>
    <div class="btnsSaibaMais">
        <span>SAIBA MAIS SOBRE:</span>
        <a href="/carenet/longevidade">Longevidade</a>
        <a href="/carenet/4-dimensoes">4 Dimensões</a>
        <a href="/carenet/desafios">Desafios</a>
        <a href="/carenet/trueage">TrueAge&reg;</a>
    </div>

    <div class="div_image_resized">
        <img src="/assets/img-custom/klip-carenet.png" alt=""/>
    </div>

    <div class="gettoknow">
        <a class="gettoknow_klip gettoknow_img" href="/klip">
            <img src="/assets/img-custom/icon-dispositivo.png" alt=""/>
            <br/>
            <span class="cnText">Klip</span>
        </a>
        <img class="gettoknow_main" src="/assets/img-custom/arrows.png" alt=""/>
        <a class="gettoknow_app gettoknow_img" href="/app">
            <img src="/assets/img-custom/icon-app.png" alt=""/>
            <br/>
            <span class="cnText">App</span>
        </a>
    </div>


