
    <div class="halfLogo">
        <img src="/assets/img-custom/logo-spacer-b.png" alt=""/>
    </div>

    <div class="carenet_info_box div_image_resized">
        <img src="/assets/img-custom/main-abertura_pt.png" alt="" />
    </div>

    <div class="content contentWithBMargin">
        <p>Bem-vindo à comunidade CARENET!
            Acreditamos que a vida saudável não
            tem que ser difícil, e vamos ajudá-lo.</p>
            <ul>
                <li>Descubra sua idade corporal (TrueAge&reg;)</li>
                <li>Monitore suas atividades.</li>
                <li>Consolide seus dados de saúde.</li>
                <li>Motive-se e inspire os outros.</li>
                <li>e muito +!</li>
            </ul>
    </div>
    <div class="contentFooter div_image_resized">
        <img src="/assets/img-custom/carenet-bottom.png" alt=""/>
    </div>
    <br/>
    <div class="btnsSaibaMais">
        <span>SAIBA MAIS SOBRE:</span>
        <a href="/carenet/longevidade">Longevidade</a>
        <a href="/carenet/4-dimensoes">4 Dimensões</a>
        <a href="/carenet/comunidade">Comunidade</a>
        <a href="/carenet/desafios">Desafios</a>
        <a href="/carenet/trueage">TrueAge&reg;</a>
    </div>

    <div class="div_image_resized">
        <img src="/assets/img-custom/klip-carenet.png" alt=""/>
    </div>

    <div class="gettoknow">
        <a class="gettoknow_klip gettoknow_img" href="/klip">
            <img src="/assets/img-custom/icon-dispositivo.png" alt=""/>
            <br/>
            <span class="cnText">Klip</span>
        </a>
        <img class="gettoknow_main" src="/assets/img-custom/arrows.png" alt=""/>
        <a class="gettoknow_app gettoknow_img" href="/app">
            <img src="/assets/img-custom/icon-app.png" alt=""/>
            <br/>
            <span class="cnText">App</span>
        </a>
    </div>


