
    <div class="halfLogo">
        <img src="/assets/img-custom/logo-spacer-b.png" alt=""/>
    </div>

    <div class="carenet_info_box div_image_resized">
        <img src="/assets/img-custom/main-trueage_pt.png" alt="" />
    </div>

    <div class="content">
        <p>O TrueAge® gera dados que te
            ajudam a entender melhor o seu
            corpo, mostrando como mudanças
            comportamentais impactam no
            processo de envelhecimento e como
            estes dados podem inspira-lo a cuidar
            melhor da sua saúde. Veja como
            funciona.</p>
        <br/>
        <img src="/assets/img-custom/icon-trueage1.png" style="vertical-align:middle; display:inline;">
        <h3 style="display:inline;">FAÇA O TESTE</h3>
        <br/>
        <p style="margin-top: 8px">Para descobrir a idade real
            do seu corpo, baixe o
            aplicativo e responda
            algumas perguntas sobre
            você e seu estilo de vida.</p>
        <br/>
        <img src="/assets/img-custom/icon-trueage2.png" style="vertical-align:middle; display:inline;">
        <h3 style="display:inline;">VEJA OS RESULTADOS</h3>
        <p style="margin-top: 8px">Seus dados serão analisados
            por um algoritmo estatístico,
            que premia atitudes
            positivas e inteligentes de
            saúde.</p>
        <br/>
        <img src="/assets/img-custom/icon-trueage3.png" style="vertical-align:middle; display:inline;">
        <h3 style="display:inline;">TENHA UMA VIDA MAIS SAUDÁVEL</h3>
        <br/>
        <p style="margin-top: 8px">Conhecendo a idade real do
            seu corpo você poderá
            adotar pequenas mudanças
            no seu dia a dia para ter uma
            vida mais longa e saudável.</p>
        <br/>
        <br/>
    </div>
    <div class="contentFooter div_image_resized">
        <img src="/assets/img-custom/carenet-bottom.png" alt=""/>
    </div>
    <br/>
    <div class="btnsSaibaMais">
        <span>SAIBA MAIS SOBRE:</span>
        <a href="/carenet/longevidade">Longevidade</a>
        <a href="/carenet/4-dimensoes">4 Dimensões</a>
        <a href="/carenet/comunidade">Comunidade</a>
        <a href="/carenet/desafios">Desafios</a>
    </div>

    <div class="div_image_resized">
        <img src="/assets/img-custom/klip-carenet.png" alt=""/>
    </div>

    <div class="gettoknow">
        <a class="gettoknow_klip gettoknow_img" href="/klip">
            <img src="/assets/img-custom/icon-dispositivo.png" alt=""/>
            <br/>
            <span class="cnText">Klip</span>
        </a>
        <img class="gettoknow_main" src="/assets/img-custom/arrows.png" alt=""/>
        <a class="gettoknow_app gettoknow_img" href="/app">
            <img src="/assets/img-custom/icon-app.png" alt=""/>
            <br/>
            <span class="cnText">App</span>
        </a>
    </div>

