
    <div class="halfLogo">
        <img src="/assets/img-custom/logo-spacer-b.png" alt=""/>
    </div>

    <div class="carenet_info_box div_image_resized">
        <img src="/assets/img-custom/main-desafios_pt.png" alt="" />
    </div>

    <div class="content">
        <p>Os jogos aprimoram a qualidade de nosso cotidiano,
            combatendo problemas sociais depressão e
            obesidade, além de, claro, ser muito divertido. Você
            poderá desafiar amigos pessoalmente ou virtualmente
            via APP. Se você quer desafiar alguém au até se auto
            desafiar, o CARENET vai te ajudar!</p>
        <br/>
        <img src="/assets/img-custom/icon-desafios1.png" style="vertical-align:middle; display:inline;">
        <h3 style="display:inline;">Desafie-se</h3>
        <br/>
        <p style="margin-top: 8px">Cada dia pode ser um recomeço. Aceite um novo desafio e
            esforce-se para testar suas habilidades e os seus limites.</p>
        <br/>
        <img src="/assets/img-custom/icon-desafios2.png" style="vertical-align:middle; display:inline;">
        <h3 style="display:inline;">Atinja Prêmios em grupo</h3>
        <p style="margin-top: 8px">Você pode montar grupos com desafios personalizados, e
            contar com o senso colaborativo para atingir seus objetivos.</p>
        <br/>
        <img src="/assets/img-custom/icon-desafios3.png" style="vertical-align:middle; display:inline;">
        <h3 style="display:inline;">Competições reais</h3>
        <br/>
        <p style="margin-top: 8px">Procure desafios e competições reais na rede Carenet, onde
            a pressão dos grupos o fará atingir metas mais altas.</p>
        <br/>
        <br/>
    </div>
    <div class="contentFooter div_image_resized">
        <img src="/assets/img-custom/carenet-bottom.png" alt=""/>
    </div>
    <br/>
    <div class="btnsSaibaMais">
        <span>SAIBA MAIS SOBRE:</span>
        <a href="/carenet/longevidade">Longevidade</a>
        <a href="/carenet/4-dimensoes">4 Dimensões</a>
        <a href="/carenet/comunidade">Comunidade</a>
        <a href="/carenet/trueage">TrueAge&reg;</a>
    </div>

    <div class="div_image_resized">
        <img src="/assets/img-custom/klip-carenet.png" alt=""/>
    </div>

    <div class="gettoknow">
        <a class="gettoknow_klip gettoknow_img" href="/klip">
            <img src="/assets/img-custom/icon-dispositivo.png" alt=""/>
            <br/>
            <span class="cnText">Klip</span>
        </a>
        <img class="gettoknow_main" src="/assets/img-custom/arrows.png" alt=""/>
        <a class="gettoknow_app gettoknow_img" href="/app">
            <img src="/assets/img-custom/icon-app.png" alt=""/>
            <br/>
            <span class="cnText">App</span>
        </a>
    </div>


