
    <div class="halfLogo">
        <img src="/assets/img-custom/logo-spacer-b.png" alt=""/>
    </div>

    <div class="carenet_info_box div_image_resized">
        <img src="/assets/img-custom/main-longevidade_pt.png" alt="" />
    </div>

    <div class="content">
        <p>Longevidade, o maior sonho humano está um
        passo mais próximo. O século 20 já nos legou um
        presente fabuloso: mais 30 anos de vida, em média.</p>
        <br/>
        <p>E estes 30 anos não estão no final do seu ciclo de
        vida, eles formam uma fase nova e empolgante no
        seu meio de vida, durante seu período mais
        produtivo e ativo.</p>
        <br/>
        <p>Mas para desfrutar este ciclo de vida
        superdimensionado, é necessário tomar conta de
        você hoje. Comece a monitorar suas atividades e
        viva mais.</p>
        <br/>
    </div>
    <div class="contentFooter div_image_resized">
        <img src="/assets/img-custom/carenet-bottom.png" alt=""/>
    </div>
    <br/>
    <div class="btnsSaibaMais">
        <span>SAIBA MAIS SOBRE:</span>
        <a href="/carenet/4-dimensoes">4 Dimensões</a>
        <a href="/carenet/comunidade">Comunidade</a>
        <a href="/carenet/desafios">Desafios</a>
        <a href="/carenet/trueage">TrueAge&reg;</a>
    </div>

    <div class="div_image_resized">
        <img src="/assets/img-custom/klip-carenet.png" alt=""/>
    </div>

    <div class="gettoknow">
        <a class="gettoknow_klip gettoknow_img" href="/klip">
            <img src="/assets/img-custom/icon-dispositivo.png" alt=""/>
            <br/>
            <span class="cnText">Klip</span>
        </a>
        <img class="gettoknow_main" src="/assets/img-custom/arrows.png" alt=""/>
        <a class="gettoknow_app gettoknow_img" href="/app">
            <img src="/assets/img-custom/icon-app.png" alt=""/>
            <br/>
            <span class="cnText">App</span>
        </a>
    </div>


