<div class="title">
    <img src="/assets/img-custom/fundo-loja-texto.png" style="position: relative; top: 0; left: 0;"/>
    <img src="/assets/img-custom/texto-termosuso.png" style="position: absolute; top: 0; left: 0;"/>
</div>

  <div class="contentConditions" id="inicio">
    Clique no item abaixo para acessar o conteúdo:
    <br/><br/>
    <ul>
        <li><a href="#terms" class="blackText">Termos de Uso</a></li>
        <li><a href="#policy" class="blackText">Política de Privacidade</a></li>
    </ul>
  </div>
    <hr/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <div class="contentConditions" id="terms">
      <h2 class="blackText">Termos de Uso</h2>
      <p>Ao acessar e/ou utilizar este site e seus aplicativos (“Plataforma Carenet”), o visitante e/ou usuário cadastrado (em conjunto definidos como “Usuário”) aceita(m) e concorda(m) que:</p>
      <br/>
      <p>O Usuário é o único e exclusivo titular e responsável pela clareza, objetividade e precisão das informações pessoais que cadastrar voluntariamente no software/sistema (“Informações Pessoais”);</p>
      <p>A Carenet utilizará as Informações Pessoais do Usuário para processar e lhe fornecer informações personalizadas sobre saúde e bem estar (“Informações Personalizadas”), por meio da Plataforma Carenet;</p>
      <p>A Carenet também utilizará as Informações Pessoais dos seus Usuários, de forma não identificada e agregada a informações de outros Usuários para, incluindo, mas não se limitando a, gerar dados e levantamentos estatísticos, bem como para gerar novas funcionalidades e conteúdos para a Plataforma Carenet, sem, contudo, identificar o Usuário que as forneceu; a Carenet poderá, ainda, realizar análises estatísticas sobre o comportamento do usuário, de forma agregada e não identificável, a fim de medir o interesse e o uso de diversas áreas e características da Plataforma Carenet;</p>
      <p>A Carenet não poderá divulgar Informações Pessoais identificáveis do Usuário a terceiros, sem o seu consentimento prévio, salvo se assim for exigido por lei ou determinação judicial, ou demais casos previstos em sua Política de Privacidade;</p>
      <p>A Carenet adota mecanismos e ferramentas para aumentar a privacidade dos dados e ajudar a prevenir a perda, mau uso ou alteração das informações sob seu controle, garantindo a segurança de acesso até o limite daqueles;</p>
      <p>A Carenet não será responsável pelas informações que o Usuário compartilhar com outros usuários, com grupos de Usuários do software e nem por aquelas que o usuário compartilhar por meio de vínculos com outras redes sociais;</p>
      <p> Plataforma Carenet foi projetado para gerar Informações Personalizadas a partir de dados fornecidos pelos usuários, tendo, portanto, finalidade meramente educacional, de orientação e estatística;</p>
      <p>A Plataforma Carenet não pode e não deve ser entendido como um diagnóstico médico ou como um substituto a consultas com um profissional da medicina; as Informações Personalizadas, igualmente, não poderão ser utilizadas para diagnosticar ou tratar um problema de saúde ou doença, devendo o Usuário procurar um profissional de sua confiança caso busque uma avaliação precisa sobre sua condição;</p>
      <p>Para fornecer informações personalizadas sobre saúde e bem estar, a Plataforma Carenet leva em consideração dados populacionais e padrões estatísticos, além das Informações Pessoais do Usuário, de modo que, pode apresentar resultados “falsos positivos” e/ou “falsos negativos” (conforme conceitos de probabilidade);</p>
      <p>A Carente aconselha o Usuário a consultar regularmente, e sempre que necessário, seu médico de confiança;</p>
      <p>A utilização da Plataforma Carenet está sujeita aos termos e condições disponíveis em www.carenet.com.br, ficando o usuário obrigado a cumpri-las; bem como a termos e condições de parceiros de negócio da Carenet, quando aplicável e assim notificado ao Usuário;</p>
      <p>Leu e compreendeu os Termos de Uso e concorda em se sujeitar às suas condições;</p>
      <p>É pessoa capaz, na acepção jurídica do termo.</p>
      <a href="" class="backToTopLink blackText">Voltar</a>
    </div>
    <hr/>
    <br/>
    <br/>
    <br/>
    <br/>
    <div class="contentConditions" id="policy">
        <h2 class="blackText">Política de Privacidade</h2>
        <p>A Carenet leva a segurança das informações muito a sério. Independentemente de ser um Usuário ou um simples visitante de nossa página virtual ou aplicativo, nós tratamos todas as informações que recebemos e/ou armazenamos como Informações Pessoais. Abaixo, expomos nossas premissas no manuseio das informações.
        <br/>
        <p>A Carenet somente coletará e/ou armazenará as Informações Pessoais identificáveis do Usuário se este as fornecer voluntariamente; entende-se como Informações Pessoais identificáveis aquelas em que é possível saber qual o Usuário que forneceu a informação.</p>
        <p>A Carenet não poderá divulgar Informações Pessoais do Usuário a terceiros, de forma identificada, sem o seu consentimento prévio, exceto quando for exigido por lei, determinado pelo Poder Judiciário ou outro órgão competente para tanto, ou se exigido pelas circunstâncias, dentre outros.</p>
        <p>A Carenet poderá utilizar Informações Pessoais do Usuário, de forma não identificada e agregada a informações de outros Usuários, oriundas do perfil do usuário e/ou outras informações de uso da Plataforma Carenet, para, incluindo, mas não se limitando a, gerar dados e levantamentos estatísticos, bem como para gerar novas funcionalidades e conteúdos para a Plataforma Carenet; a Carenet poderá, ainda, realizar análises estatísticas sobre o comportamento do usuário, de forma agregada e não identificável, a fim de medir o interesse e o uso de diversas áreas e características da Plataforma Carenet.</p>
        <p>Caso um Usuário queira realizar a exclusão de seus registros, a Carenet, mediante solicitação expressa e escrita, poderá excluir da Plataforma Carenet o nome de usuário e Informações Pessoais identificáveis (ou seja, a vinculação entre suas informações e seus dados de Usuário), mas manterá as informações fornecidas para fins de histórico e base estatística, sem qualquer tipo de identificação.</p>
        <p>Empresas direta ou indiretamente ligadas à Carenet, por meio de laços societários ou semelhança de sócios, não são considerados terceiros para efeitos de cessão de informações.</p>
        <p>A Carenet poderá ceder as informações relativas aos Usuários da Plataforma Carenet em caso de reorganização societária ou cessão de ativos, independentemente de aviso prévio aos usuários.</p>
        <p>A Plataforma Carenet usa as tecnologias disponíveis para aumentar a privacidade dos dados e ajudar a prevenir a perda, mau uso ou alteração das informações sob a gerência da Carenet; estas tecnologias, entretanto, podem, eventualmente, não garantir ou proteger a total privacidade das informações voluntariamente inseridas pelo Usuário na Plataforma Carenet, não podendo a Carenet ser responsabilizada por perdas, extravio, roubo, furto, ou qualquer outra forma de obtenção ou divulgação de informação quando ela não for voluntariamente realizada pela Carenet.</p>
        <a href="" class="backToTopLink blackText">Voltar</a>
    </div>
