<div class="condicoes_gerais">
    <a href="/condicoes">Condições Gerais</a>
</div>

<!-- footer wrapper starts -->
<div class="footerWrapper">
    <!-- copyright wrapper starts -->
    <div class="copyrightWrapper">
        <!-- copyright starts -->
        <span class="copyright">&copy; Carenet Longevity 2014</span>
        <!-- copyright ends -->
        <!-- back to top btn starts -->
        <a href="" class="backToTopButton"></a>
        <!-- back to top btn ends -->
    </div>
    <!-- copyright wrapper ends -->
</div>
<!-- footer wrapper ends -->

</div>
<!-- website wrapper ends -->
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-43245167-1', 'm.carenet.com.br');
    ga('send', 'pageview');

</script>
</body>
</html>
