

<div class="halfLogo">
    <img src="/assets/img-custom/logo-spacer-b.png" alt=""/>
</div>

<p class="introText">A Carenet é uma plataforma de monitoramento de bem-estar que ajuda você a viver mais saudável.</p>

<!-- slider wrapper starts -->
<div class="sliderOuterWrapper noPadding noMargin">
    <div class="sliderWrapper">
        <div class="mainSlider" id="mainSlider">
            <a href=""><img src="/assets/img-custom/main-abertura_pt.png" alt="" /></a>
            <a href=""><img src="/assets/img-custom/main-4dimensoes_pt.png" alt="" /></a>
            <a href=""><img src="/assets/img-custom/main-comunidade_pt.png" alt="" /></a>
            <a href=""><img src="/assets/img-custom/main-longevidade_pt.png" alt="" /></a>
            <a href=""><img src="/assets/img-custom/main-trueage-base.png" alt="" /></a>
            <a href=""><img src="/assets/img-custom/main-desafios_pt.png" alt="" /></a>
        </div>
    </div>
</div>
<!-- slider wrapper ends -->

<div id="mediabox">
    <div class="wrapper">
        <ul class="slider_text">
            <li><h2>Acreditamos que a vida saudável não tem que ser difícil, e vamos ajudá-lo.</h2><a href="/carenet">Saiba Mais</a></li>
            <li><h2>Fique em forma, durma melhor, viva mais!</h2><a href="/carenet/4-dimensoes">Saiba Mais</a></li>
            <li><h2>Cuide melhor da sua familia</h2><a href="/carenet/comunidade">Saiba Mais</a></li>
            <li><h2>Viva melhor para viver mais</h2><a href="/carenet/longevidade">Saiba Mais</a></li>
            <li><h2>Você sabe a sua idade real?</h2><a href="/carenet/trueage">Saiba Mais</a></li>
            <li><h2>Desafie-se e alcançe os seus objetivos.</h2><a href="/carenet/desafios">Saiba Mais</a></li>
        </ul>
    </div>
</div>

<br/>

<div class="">
    <a href="/klip" class="div_image_resized">
        <img src="/assets/img-custom/box-klip_pt.png" alt=""/>
    </a>
</div>

<div class="box30">
    <a href="#popup_home" class="inline div_image_resized">
        <img src="/assets/img-custom/30indicadores_pt.png" alt=""  />
    </a>
</div>

<div style='display:none; text-align: center'>
    <div id='popup_home' style='background:#000; text-align: center; width: 100%;'>
        <img src="/assets/img-custom/indicadores/popup01_pt.png" alt=""/>
        <div class="commonIndicator moveIndicator"><a href="#popup_move" class="inline"></a></div>
        <div class="commonIndicator eatIndicator"><a href="#popup_eat" class="inline"></a></div>
        <div class="commonIndicator bmIndicator"><a href="#popup_bm" class="inline"></a></div>
        <div class="commonIndicator sleepIndicator"><a href="#popup_sleep" class="inline"></a></div>
        <div class="commonIndicator closeButton"><a href="javascript:$.colorbox.close();"></a></div>
    </div>
    <div id='popup_move' style='background:#000; width: 100%;'>
        <img src="/assets/img-custom/indicadores/popup02_pt.png" alt=""/>
        <div class="commonIndicator backButton"><a href="#popup_home" class="inline"></a></div>
        <div class="commonIndicator closeButton"><a href="javascript:$.colorbox.close();"></a></div>
        <div class="scroll">
            <ul>
                <li>Tipo de Atividade</li>
                <li>Distância</li>
                <li>Passos dados</li>
                <li>Meta</li>
                <li>Calorias Queimadas</li>
                <li>Tempo de atividade</li>
                <li>Maior periodo</li>
                <li>Nível</li>
                <li>Degraus subidos</li>
                <li>Velocidade</li>
                <li>GPS</li>
            </ul>
        </div>
    </div>
    <div id='popup_eat' style='background:#000; width: 100%;'>
        <img src="/assets/img-custom/indicadores/popup03_pt.png" alt=""/>
        <div class="commonIndicator backButton"><a href="#popup_home" class="inline"></a></div>
        <div class="commonIndicator closeButton"><a href="javascript:$.colorbox.close();"></a></div>
        <div class="scroll">
            <ul>
                <li>Ingestão Calórica</li>
                <li>Informações nutricionais</li>
                <li>Tipo de refeição</li>
                <li>Descrição</li>
            </ul>
        </div>
    </div>
    <div id='popup_bm' style='background:#000; width: 100%;'>
        <img src="/assets/img-custom/indicadores/popup05_pt.png" alt=""/>
        <div class="commonIndicator backButton"><a href="#popup_home" class="inline"></a></div>
        <div class="commonIndicator closeButton"><a href="javascript:$.colorbox.close();"></a></div>
        <div class="scroll">
            <ul>
                <li>Humor</li>
                <li>Peso</li>
                <li>Massa Corporal</li>
                <li>Gordura Corporal</li>
                <li>Colesterol</li>
                <li>Temperatura Corporal</li>
                <li>Pulso</li>
                <li>Pressão Arterial</li>
            </ul>
        </div>
    </div>
    <div id='popup_sleep' style='background:#000; width: 100%;'>
        <img src="/assets/img-custom/indicadores/popup04_pt.png" alt=""/>
        <div class="commonIndicator backButton"><a href="#popup_home" class="inline"></a></div>
        <div class="commonIndicator closeButton"><a href="javascript:$.colorbox.close();"></a></div>
        <div class="scroll">
            <ul>
                <li>Sono profundo</li>
                <li>Sono leve</li>
                <li>Adormeceu</li>
                <li>Horas acordadas</li>
                <li>Horas dormidas</li>
                <li>Tempo de cama</li>
                <li>Meta</li>
            </ul>
        </div>
    </div>
</div>

<div class="socialbox">
    <a class="socialbox_facebook" href="https://www.facebook.com/CarenetLongevity">
        <img class="autosizeImg" src="/assets/img-custom/facebook-botao.png" alt=""/>
        <span class="cnText">Curta</span>
    </a>
    <img class="socialbox_carenet" src="/assets/img-custom/carenet-social.png" alt=""/>
    <a class="socialbox_twitter" href="https://twitter.com/Carenet_TrueAge">
        <img class="autosizeImg" src="/assets/img-custom/twitter-botao.png" alt=""/>
        <span class="cnText">Siga</span>
    </a>
</div>
