  <div class="title">
      <img src="/assets/img-custom/fundo-loja-texto.png" style="position: relative; top: 0; left: 0;"/>
      <img src="/assets/img-custom/texto-loja.png" style="position: absolute; top: 0; left: 0;"/>
  </div>

  <!-- slider wrapper ends -->
  <div class="product-header">
      <img src="/assets/img-custom/title-spacer.png" alt=""/>
      <div class="row product-top-box">
          <div class="primary-info col">
              <span class="titleText">BIOSSENSOR KLIP CARENET</span>
          </div>
      </div>
      <!-- slider wrapper starts -->
      <div class="sliderOuterWrapper photo-container">
          <div class="sliderWrapper">
              <div class="mainSlider" id="mainSlider">
                  <a href=""><img src="/assets/img-custom/produtos/fotos-variacao01.png" alt="" /></a>
                  <a href=""><img src="/assets/img-custom/produtos/fotos-variacao02.png" alt="" /></a>
                  <a href=""><img src="/assets/img-custom/produtos/fotos-variacao03.png" alt="" /></a>
                  <a href=""><img src="/assets/img-custom/produtos/fotos-variacao04.png" alt="" /></a>
              </div>
          </div>
      </div>
      <!-- slider wrapper ends -->
  </div>

  <div class="div_image_resized">
      <img src="/assets/img-custom/product-spacer.png" alt=""/>
  </div>

  <div class="product-box">
      <div class="topic">
            <p>
                O biossensor KLIP Carenet será seu maior aliado na busca de seus objetivos para melhorar sua saúde e bem-estar. Este dispositivo vai te monitorar 24h por dia, colhendo informações importantes e montando gráficos completos e objetivos.
            </p>
            <p>Monitore seus exercícios, seu sono e muito mais. Começe a cuidar de você HOJE.</p>
            <p style="color: #51b0a8">
                Atenção: o KLIP Carenet não é à prova d'água.
            </p>
        </div>

      <div class="row">
            <div class="col features">
                <ul>
                    <li class="atividades">
                        <h3><i></i>Atividades diárias</h3>
                        <p>
                            Monitora seus passos, distância
                            percorrida, calorias queimadas e o
                            alcance da sua meta diária através de
                            um visor integrado.
                        </p>
                    </li>
                    <li class="monitoramento">
                        <h3><i></i>Monitoramento do sono</h3>
                        <p>
                            Controla sua qualidade do sono.
                        </p>
                    </li>
                    <li class="compartilhamento">
                        <h3>
                            <i></i>
                            Compartilhamento e sincronização online
                        </h3>
                        <p>
                            Transferência de dados das suas atividades através de cabo USB.
                        </p>
                    </li>
                    <li class="gerenciamento">
                        <h3><i></i>Gerenciamento online</h3>
                        <p>
                            Monitoramento online e mobile de seus objetivos de saúde e metas alcançadas.
                        </p>
                    </li>
                </ul>
            </div>
        </div>

      <div class="row product-top-box">
          <div class="availability">
              COMPRE PELO NOSSO APLICATIVO AGORA!
          </div>
          <div class="primary-info col">
              <div class="price-info">
                  <img src="/assets/img-custom/10x.png" style="float: right; width: 40%; height: auto; white-space: nowrap; text-align: right;" alt=""/>
                  <span class="price" >R$ 199,00</span>
              </div>
          </div>
      </div>

    <br/>
    <div >
        <img src="/assets/img-custom/icon-cifra.png" style="width: 15px; float: left; margin-right: 5px" alt=""/>
        <h3 class="product-section-title">Formas de pagamento</h3>
    </div>

    <img src="/assets/img-custom/icon-bcash.png" alt="" style="width: 30%; height: auto;"/>

    <div class="formasPagamentoDetalhe">
        <img src="/assets/img-custom/icon-spacer-formas.png" class="formasPagamentoDetalheTexto" alt=""/>
        <span>Cartões de Crédito</span>
        <img src="/assets/img-custom/icon-credito.png" class="formasPagamentoDetalheImage" alt=""/>
    </div>
    <div class="formasPagamentoDetalhe">
        <img src="/assets/img-custom/icon-spacer-formas.png" class="formasPagamentoDetalheTexto" alt=""/>
        <span>Cartões de Débito</span>
        <img src="/assets/img-custom/icon-debito.png" class="formasPagamentoDetalheImage" alt=""/>
    </div>
    <div class="formasPagamentoDetalhe">
        <img src="/assets/img-custom/icon-spacer-formas.png" class="formasPagamentoDetalheTexto" alt=""/>
        <span>Boleto Bancário</span>
        <img src="/assets/img-custom/icon-debito.png" class="formasPagamentoDetalheImage" alt=""/>
    </div>
  </div>